### ISSUE TITLE
TypeError: __inc__() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by ZhaoningYu1996** [rusty1s/himp-gnn#13]
Hi,

When I am running train_tox21.py, it shows TypeError: __inc__() takes 3 positional arguments but 4 were given.
Could you help me with this?

Traceback (most recent call last):
  File "/home/znyu/projects/Explainer/train_himp.py", line 109, in <module>
    loss = train(epoch)
  File "/home/znyu/projects/Explainer/train_himp.py", line 60, in train
    for data in train_loader:
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch_geometric/loader/dataloader.py", line 39, in __call__
    return self.collate(batch)
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch_geometric/loader/dataloader.py", line 19, in collate
    return Batch.from_data_list(batch, self.follow_batch,
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch_geometric/data/batch.py", line 69, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 85, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 156, in _collate
    incs = get_incs(key, values, data_list, stores)
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 207, in get_incs
    repeats = [
  File "/home/znyu/anaconda3/envs/pyg202/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 208, in <listcomp>
    data.__inc__(key, value, store)
TypeError: __inc__() takes 3 positional arguments but 4 were given

**Comment by rusty1s** [comment]
Thanks for letting me know. This should be now fixed in master.

**Comment by Soroushstr** [comment]
I still do have the same issue. Is it fixed? any idea on how to fix it?

**Comment by rusty1s** [comment]
Which version of PyG are you on?

**Comment by Soroushstr** [comment]
I'm using torch-geometric 2.6.1. Just managed to solve the issue by changing the following section in the collate.py file, as https://github.com/pyg-team/pytorch_geometric/issues/4358#issuecomment-1515623604 suggested!
