### ISSUE TITLE
DataLoader error

### ISSUE THREAD

**Issue by danielzuegner** [rusty1s/himp-gnn#2]
Hi Matthias,

Thanks for providing the implementation to your interesting paper. I've tried running the `train_ogbhiv.py` script but I'm encountering an error.

This is the output of `python train_ogbhiv.py`:
```
Namespace(device=0, dropout=0.5, epochs=50, hidden_channels=64, no_inter_message_passing=False, num_layers=2)

Run 1:

Traceback (most recent call last):
  File "train_ogbhiv.py", line 96, in <module>
    loss = train(epoch)
  File "train_ogbhiv.py", line 58, in train
    for data in train_loader:
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 34, in __call__
    return self.collate(batch)
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 15, in collate
    return Batch.from_data_list(batch, self.follow_batch)
  File "/nfs/staff-ssd/zuegnerd/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 53, in from_data_list
    item = item + cum if cum != 0 else item
RuntimeError: bool value of Tensor with more than one value is ambiguous
```

Versions installed:
`torch_geometric==1.6.0`   
`torch==1.4.0`   
`ogb==1.2.1`   

Do you have an idea what's going on and how to fix it?

Thanks again!

Daniel

**Comment by rusty1s** [comment]
Hi Daniel, thanks for your interest! I‘m really sorry about  this error. It got introduced in PyG 1.6.0, but is already fixed in master. You can fix that by cloning PyG from GitHub and installing it from source, or wait for the PyG 1.6.1 bugfix release (will probably be released around next week).

**Comment by danielzuegner** [comment]
Thanks! I simply downgraded to PyG 1.5.0 for now and it's working.
