### ISSUE TITLE
RunetimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by sooheon** [rusty1s/himp-gnn#3]
I am on recent pytorch, so this is kind of to be expected, but just a heads up.

Versions:
```
dependencies:
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
pip:
    - torch-cluster==1.5.6
    - torch-geometric==1.6.0
    - torch-scatter==2.0.5
    - torch-sparse==0.6.6
    - torch-spline-conv==1.2.0
```

Error:

```
Traceback (most recent call last):
  File "train_ogbhiv.py", line 96, in <module>
    loss = train(epoch)
  File "train_ogbhiv.py", line 58, in train
    for data in train_loader:
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch_geometric/data/dataloader.py", line 34, in __call__
    return self.collate(batch)
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch_geometric/data/dataloader.py", line 15, in collate
    return Batch.from_data_list(batch, self.follow_batch)
  File "/home/sooheon_k_gmail_com/anaconda3/envs/dl/lib/python3.7/site-packages/torch_geometric/data/batch.py", line 53, in from_data_list
    item = item + cum if cum != 0 else item
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

**Comment by rusty1s** [comment]
Please see https://github.com/rusty1s/himp-gnn/issues/2.

**Comment by sooheon** [comment]
Thanks!
