### ISSUE TITLE
AttributeError: 'Batch' object has no attribute 'x_clique'

### ISSUE THREAD

**Issue by devnkong** [rusty1s/himp-gnn#4]
Hello Matthias,

I was trying to run the command `python train_ogbhiv.py`, but yield the error below. 

```
Traceback (most recent call last):
  File "himp-molhiv.py", line 96, in <module>
    loss = train(epoch)
  File "himp-molhiv.py", line 61, in train
    out = model(data)
  File "/cmlscratch/kong/anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfshomes/kong/projects/ogb/examples/graphproppred/mol/himp-molhiv/model.py", line 134, in forward
    x_clique = self.clique_encoder(data.x_clique.squeeze())
AttributeError: 'Batch' object has no attribute 'x_clique'
```
Would you please have a look?

BTW I'm using PyG==1.6.1, OGB==1.2.3

**Comment by rusty1s** [comment]
It seems like the `pre_transform` does not get called. Are you using an already downloaded version of `ogbg-hiv`? It might be best to remove the pre-processed dataset in `data/.../processed` and try again.

**Comment by devnkong** [comment]
Found that I was actually using 1.6.0. After upgrading it's fine. Thank you!
